name: 'Deploy to GitHub Pages'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

concurrency:
  cancel-in-progress: true
  group: 'github-pages'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:

      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Configure Pages'
        uses: 'actions/configure-pages@v5'

      - name: 'Upload artifact'
        uses: 'actions/upload-pages-artifact@v3'
        with:
          path: 'web/'

  deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Deploy to GitHub Pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@v1'
